from fastapi import APIRouter, Depends, UploadFile, File, Form, Response, status, HTTPException
from typing import Optional
from app.services.user_service import get_current_user
from app.models.user import User
from app.services.speech_service import transcribe_audio, synthesize_speech
from pydantic import BaseModel

router = APIRouter(prefix="/voice", tags=["Voice"])

class SynthesizeRequest(BaseModel):
    text: str

@router.post("/transcribe", status_code=status.HTTP_200_OK)
async def transcribe(
    file: UploadFile = File(...),
    current_user: User = Depends(get_current_user),
):
    """
    Accepts an audio file and returns the transcribed text via ElevenLabs STT.
    """
    file_bytes = await file.read()
    # Simple validation of file size
    from app.core.config import settings
    if len(file_bytes) > settings.SPEECH_MAX_UPLOAD_MB * 1024 * 1024:
        raise HTTPException(status_code=413, detail=f"File exceeds {settings.SPEECH_MAX_UPLOAD_MB}MB")
        
    text = await transcribe_audio(file_bytes, file.filename)
    return {"text": text}

@router.post("/synthesize")
async def synthesize(
    request: SynthesizeRequest,
    current_user: User = Depends(get_current_user),
):
    """
    Accepts text and returns an audio file generated by ElevenLabs TTS.
    """
    audio_bytes = await synthesize_speech(request.text)
    
    # Return audio as binary response
    return Response(
        content=audio_bytes, 
        media_type="audio/mpeg",
        headers={
            "Content-Disposition": 'inline; filename="response.mp3"'
        }
    )
